In [3]:
import pandas as pd
df = pd.read_csv("/content/lego_sets.csv")
theme = pd.read_csv("/content/parent_themes.csv")
theme.head(50)

     id                      name  is_licensed
0     1                   Technic        False
1    22                   Creator        False
2    50                      Town        False
3   112                    Racers        False
4   126                     Space        False
5   147                   Pirates        False
6   155         Modular Buildings        False
7   158                 Star Wars         True
8   186                    Castle        False
9   204             Designer Sets        False
10  206                  Seasonal        False
11  233                     Train        False
12  246              Harry Potter         True
13  252              Architecture        False
14  254               Bulk Bricks        False
15  258                Mindstorms        False
16  263  Pirates of the Caribbean         True
17  264             Indiana Jones         True
18  269                      Cars         True
19  270                    Ben 10         True
20  271          Prince of Persia         True
21  272     SpongeBob SquarePants         True
22  273                   Studios        False
23  275                 Toy Story         True
24  276                Sculptures        False
25  278                Model Team        False
26  279                 4 Juniors        False
27  296               Adventurers        False
28  301                     Other        False
29  302                    Agents        False
30  304                Alpha Team        False
31  307                  Aquazone        False
32  315                  Atlantis        False
33  317                    Avatar         True
34  318                  Belville        False
35  324                  Bionicle        False
36  363                      Boat        False
37  364  Building Set with People        False
38  365                   Classic        False
39  384                 Dino 2010        False
40  385               Dino Attack        False
41  386                 Dinosaurs        False
42  387                 Discovery        False
43  388     Disney's Mickey Mouse         True
44  389                 Exo-Force        False
45  390                  Fabuland        False
46  397                   Factory        False
47  398         FIRST LEGO League        False
48  399                 Freestyle        False
49  400              Hero Factory        False

In [5]:
df.head()

,set_num,name,year,num_parts,theme_name,parent_theme
0,00-1,Weetabix Castle,1970,471.0,Castle,Legoland
1,0011-2,Town Mini-Figures,1978,NaN,Supplemental,Town
2,0011-3,Castle 2 for 1 Bonus Offer,1987,NaN,Lion Knights,Castle
3,0012-1,Space Mini-Figures,1979,12.0,Supplemental,Space
4,0013-1,Space Mini-Figures,1979,12.0,Supplemental,Space

In [5]:
merged = df.merge(theme, left_on = 'parent_theme', right_on = 'name')
merged.drop(columns = 'name_y', inplace = True)
merged.head()

,set_num,name_x,year,num_parts,theme_name,parent_theme,id,is_licensed
0,00-1,Weetabix Castle,1970,471.0,Castle,Legoland,411,False
1,00-2,Weetabix Promotional House 1,1976,NaN,Building,Legoland,411,False
2,00-3,Weetabix Promotional House 2,1976,NaN,Building,Legoland,411,False
3,00-4,Weetabix Promotional Windmill,1976,126.0,Building,Legoland,411,False
4,00-7,Weetabix Promotional Lego Village,1976,NaN,Building,Legoland,411,False

In [17]:
merged[merged['set_num'].isnull()].shape

(153, 8)

In [21]:
licensed = merged[merged['is_licensed']]
licensed = licensed.dropna(subset = ['set_num'])
licensed.head()
star_wars = licensed[licensed['parent_theme'] == 'Star wars']
the_force = int(star_wars.shape[0]/ licensed.shape[0] * 100)
print(the_force)

0

In [34]:
licensed_sorted = licensed.sort_values('year')
licensed_sorted['count'] = 1
summed_df = licensed_sorted.groupby(['year', 'parent_theme']).sum().reset_index()
max_df = summed_df.sort_values('count', ascending = False).drop_duplicates(['year'])
max_df.sort_values('year', inplace = True)
max_df

<ipython-input-34-848a5dd6b7ef>:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  summed_df = licensed_sorted.groupby(['year', 'parent_theme']).sum().reset_index()

    year  parent_theme  num_parts     id  is_licensed  count
0   1999     Star Wars     1384.0   2054           13     13
2   2000     Star Wars     2580.0   4108           26     26
4   2001     Star Wars     2949.0   2212           14     14
6   2002     Star Wars     4735.0   4424           28     28
9   2003     Star Wars     6660.0   5056           32     32
12  2004     Star Wars     1659.0   3160           20     20
16  2005     Star Wars     4730.0   4424           28     28
20  2006     Star Wars     2769.0   1738           11     11
24  2007     Star Wars    11361.0   2528           16     16
28  2008     Star Wars     6865.0   3634           23     23
32  2009     Star Wars     3953.0   6162           39     39
36  2010     Star Wars     6003.0   4740           30     30
42  2011     Star Wars     3451.0   5056           32     32
47  2012     Star Wars     6769.0   6794           43     43
52  2013     Star Wars     6159.0   5530           35     35
59  2014     Star Wars     8293.0   7110           45     45
67  2015     Star Wars    11410.0   9164           58     58
76  2016     Star Wars     6934.0   9638           61     61
82  2017  Super Heroes    13123.0  34704           72     72

In [35]:
new_era = 2017

In [46]:
clean_df = merged[~merged['set_num'].isnull()]
clean_df['count'] = 1
sets_per_year = clean_df.groupby(['year']).sum().reset_index()[['year', 'count']]
for index, row in sets_per_year.iterrows():
  print(row)

year     1950
count       7
Name: 0, dtype: int64
year     1953
count       4
Name: 1, dtype: int64
year     1954
count      14
Name: 2, dtype: int64
year     1955
count      28
Name: 3, dtype: int64
year     1956
count      12
Name: 4, dtype: int64
year     1957
count      21
Name: 5, dtype: int64
year     1958
count      42
Name: 6, dtype: int64
year     1959
count       4
Name: 7, dtype: int64
year     1960
count       3
Name: 8, dtype: int64
year     1961
count      17
Name: 9, dtype: int64
year     1962
count      40
Name: 10, dtype: int64
year     1963
count      18
Name: 11, dtype: int64
year     1964
count      11
Name: 12, dtype: int64
year     1965
count      10
Name: 13, dtype: int64
year     1966
count      89
Name: 14, dtype: int64
year     1967
count      21
Name: 15, dtype: int64
year     1968
count      25
Name: 16, dtype: int64
year     1969
count      69
Name: 17, dtype: int64
year     1970
count      29
Name: 18, dtype: int64
year     1971
count      45
Name: 19, dtype: int64
year     1972
count      38
Name: 20, dtype: int64
year     1973
count      68
Name: 21, dtype: int64
year     1974
count      39
Name: 22, dtype: int64
year     1975
count      31
Name: 23, dtype: int64
year     1976
count      68
Name: 24, dtype: int64
year     1977
count      92
Name: 25, dtype: int64
year     1978
count      73
Name: 26, dtype: int64
year     1979
count      82
Name: 27, dtype: int64
year     1980
count      88
Name: 28, dtype: int64
year     1981
count      79
Name: 29, dtype: int64
year     1982
count      76
Name: 30, dtype: int64
year     1983
count      57
Name: 31, dtype: int64
year     1984
count      76
Name: 32, dtype: int64
year     1985
count     139
Name: 33, dtype: int64
year     1986
count     123
Name: 34, dtype: int64
year     1987
count     209
Name: 35, dtype: int64
year     1988
count      68
Name: 36, dtype: int64
year     1989
count     114
Name: 37, dtype: int64
year     1990
count      85
Name: 38, dtype: int64
year     1991
count     106
Name: 39, dtype: int64
year     1992
count     115
Name: 40, dtype: int64
year     1993
count     111
Name: 41, dtype: int64
year     1994
count     128
Name: 42, dtype: int64
year     1995
count     128
Name: 43, dtype: int64
year     1996
count     144
Name: 44, dtype: int64
year     1997
count     194
Name: 45, dtype: int64
year     1998
count     325
Name: 46, dtype: int64
year     1999
count     300
Name: 47, dtype: int64
year     2000
count     327
Name: 48, dtype: int64
year     2001
count     339
Name: 49, dtype: int64
year     2002
count     447
Name: 50, dtype: int64
year     2003
count     415
Name: 51, dtype: int64
year     2004
count     371
Name: 52, dtype: int64
year     2005
count     330
Name: 53, dtype: int64
year     2006
count     283
Name: 54, dtype: int64
year     2007
count     319
Name: 55, dtype: int64
year     2008
count     349
Name: 56, dtype: int64
year     2009
count     403
Name: 57, dtype: int64
year     2010
count     444
Name: 58, dtype: int64
year     2011
count     502
Name: 59, dtype: int64
year     2012
count     615
Name: 60, dtype: int64
year     2013
count     593
Name: 61, dtype: int64
year     2014
count     715
Name: 62, dtype: int64
year     2015
count     670
Name: 63, dtype: int64
year     2016
count     608
Name: 64, dtype: int64
year     2017
count     438
Name: 65, dtype: int64

<ipython-input-46-e06c245d7c5b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  clean_df['count'] = 1
<ipython-input-46-e06c245d7c5b>:3: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  sets_per_year = clean_df.groupby(['year']).sum().reset_index()[['year', 'count']]